# This is a sample configuration file to use on Torch.
# You can find more information about the configuration file on the wiki (WIP)

N64Hash:
  name: Game              # The name of the game; you can use any name you want.
  path: assets/example/   # The path to the ymls folder
  config:
    gbi: F3D              # You can use F3D, F3DEX, F3DEX-MK64, F3DB, F3DEX2, F3DEXB,
    sort: OFFSET          # This is how the assets are going to be sorted when generating the Header / C files. You can use OFFSET, ROFFSET for a reverse order or even specify a manual order using a list with the types.
    output:
      binary: example.otr # The name of the output binary file
      headers: include    # The name of the output headers folder
      code: code          # The name of the output code folder
  segments:               # A list with all the segmented addresses in order
    - 0x12345678