var searchData=
[
  ['objectinit_0',['ObjectInit',['../structSF64_1_1ObjectInit.html',1,'SF64']]],
  ['objinitbinaryexporter_1',['ObjInitBinaryExporter',['../classSF64_1_1ObjInitBinaryExporter.html',1,'SF64']]],
  ['objinitcodeexporter_2',['ObjInitCodeExporter',['../classSF64_1_1ObjInitCodeExporter.html',1,'SF64']]],
  ['objinitdata_3',['ObjInitData',['../classSF64_1_1ObjInitData.html',1,'SF64']]],
  ['objinitfactory_4',['ObjInitFactory',['../classSF64_1_1ObjInitFactory.html',1,'SF64']]],
  ['objinitheaderexporter_5',['ObjInitHeaderExporter',['../classSF64_1_1ObjInitHeaderExporter.html',1,'SF64']]],
  ['objinitxmlexporter_6',['ObjInitXMLExporter',['../classSF64_1_1ObjInitXMLExporter.html',1,'SF64']]],
  ['oblb_7',['Blob Resource (OBLB)',['../otr_blob.html#autotoc_md7',1,'']]],
  ['odlt_8',['Display List Resource (ODLT)',['../otr_display_list.html#autotoc_md10',1,'']]],
  ['offsetentry_9',['OffsetEntry',['../structOffsetEntry.html',1,'']]],
  ['oflt_10',['Float Resource (OFLT)',['../otr_float.html#autotoc_md14',1,'']]],
  ['omtx_11',['Matrix Resource (OMTX)',['../otr_matrix.html#autotoc_md32',1,'']]],
  ['ootanimationbinaryexporter_12',['OoTAnimationBinaryExporter',['../classOoT_1_1OoTAnimationBinaryExporter.html',1,'OoT']]],
  ['ootanimationfactory_13',['OoTAnimationFactory',['../classOoT_1_1OoTAnimationFactory.html',1,'OoT']]],
  ['ootarraybinaryexporter_14',['OoTArrayBinaryExporter',['../classOoT_1_1OoTArrayBinaryExporter.html',1,'OoT']]],
  ['ootarrayfactory_15',['OoTArrayFactory',['../classOoT_1_1OoTArrayFactory.html',1,'OoT']]],
  ['ootaudiobinaryexporter_16',['OoTAudioBinaryExporter',['../classOoT_1_1OoTAudioBinaryExporter.html',1,'OoT']]],
  ['ootaudiodata_17',['OoTAudioData',['../classOoT_1_1OoTAudioData.html',1,'OoT']]],
  ['ootaudiofactory_18',['OoTAudioFactory',['../classOoT_1_1OoTAudioFactory.html',1,'OoT']]],
  ['ootcollisionbinaryexporter_19',['OoTCollisionBinaryExporter',['../classOoT_1_1OoTCollisionBinaryExporter.html',1,'OoT']]],
  ['ootcollisiondata_20',['OoTCollisionData',['../classOoT_1_1OoTCollisionData.html',1,'OoT']]],
  ['ootcollisionfactory_21',['OoTCollisionFactory',['../classOoT_1_1OoTCollisionFactory.html',1,'OoT']]],
  ['ootcurveanimationbinaryexporter_22',['OoTCurveAnimationBinaryExporter',['../classOoT_1_1OoTCurveAnimationBinaryExporter.html',1,'OoT']]],
  ['ootcurveanimationdata_23',['OoTCurveAnimationData',['../classOoT_1_1OoTCurveAnimationData.html',1,'OoT']]],
  ['ootcurveanimationfactory_24',['OoTCurveAnimationFactory',['../classOoT_1_1OoTCurveAnimationFactory.html',1,'OoT']]],
  ['ootcutscenebinaryexporter_25',['OoTCutsceneBinaryExporter',['../classOoT_1_1OoTCutsceneBinaryExporter.html',1,'OoT']]],
  ['ootcutscenedata_26',['OoTCutsceneData',['../classOoT_1_1OoTCutsceneData.html',1,'OoT']]],
  ['ootcutscenefactory_27',['OoTCutsceneFactory',['../classOoT_1_1OoTCutsceneFactory.html',1,'OoT']]],
  ['ootlimbbinaryexporter_28',['OoTLimbBinaryExporter',['../classOoT_1_1OoTLimbBinaryExporter.html',1,'OoT']]],
  ['ootlimbdata_29',['OoTLimbData',['../classOoT_1_1OoTLimbData.html',1,'OoT']]],
  ['ootlimbfactory_30',['OoTLimbFactory',['../classOoT_1_1OoTLimbFactory.html',1,'OoT']]],
  ['ootmtxbinaryexporter_31',['OoTMtxBinaryExporter',['../classOoT_1_1OoTMtxBinaryExporter.html',1,'OoT']]],
  ['ootmtxdata_32',['OoTMtxData',['../classOoT_1_1OoTMtxData.html',1,'OoT']]],
  ['ootmtxfactory_33',['OoTMtxFactory',['../classOoT_1_1OoTMtxFactory.html',1,'OoT']]],
  ['ootnormalanimationdata_34',['OoTNormalAnimationData',['../classOoT_1_1OoTNormalAnimationData.html',1,'OoT']]],
  ['ootpathbinaryexporter_35',['OoTPathBinaryExporter',['../classOoT_1_1OoTPathBinaryExporter.html',1,'OoT']]],
  ['ootpathdata_36',['OoTPathData',['../classOoT_1_1OoTPathData.html',1,'OoT']]],
  ['ootpathfactory_37',['OoTPathFactory',['../classOoT_1_1OoTPathFactory.html',1,'OoT']]],
  ['ootplayeranimationdata_38',['OoTPlayerAnimationData',['../classOoT_1_1OoTPlayerAnimationData.html',1,'OoT']]],
  ['ootplayeranimationdatabinaryexporter_39',['OoTPlayerAnimationDataBinaryExporter',['../classOoT_1_1OoTPlayerAnimationDataBinaryExporter.html',1,'OoT']]],
  ['ootplayeranimationdatafactory_40',['OoTPlayerAnimationDataFactory',['../classOoT_1_1OoTPlayerAnimationDataFactory.html',1,'OoT']]],
  ['ootplayeranimationheaderbinaryexporter_41',['OoTPlayerAnimationHeaderBinaryExporter',['../classOoT_1_1OoTPlayerAnimationHeaderBinaryExporter.html',1,'OoT']]],
  ['ootplayeranimationheaderdata_42',['OoTPlayerAnimationHeaderData',['../classOoT_1_1OoTPlayerAnimationHeaderData.html',1,'OoT']]],
  ['ootplayeranimationheaderfactory_43',['OoTPlayerAnimationHeaderFactory',['../classOoT_1_1OoTPlayerAnimationHeaderFactory.html',1,'OoT']]],
  ['ootscenebinaryexporter_44',['OoTSceneBinaryExporter',['../classOoT_1_1OoTSceneBinaryExporter.html',1,'OoT']]],
  ['ootscenedata_45',['OoTSceneData',['../classOoT_1_1OoTSceneData.html',1,'OoT']]],
  ['ootscenefactory_46',['OoTSceneFactory',['../classOoT_1_1OoTSceneFactory.html',1,'OoT']]],
  ['ootskeletonbinaryexporter_47',['OoTSkeletonBinaryExporter',['../classOoT_1_1OoTSkeletonBinaryExporter.html',1,'OoT']]],
  ['ootskeletondata_48',['OoTSkeletonData',['../classOoT_1_1OoTSkeletonData.html',1,'OoT']]],
  ['ootskeletonfactory_49',['OoTSkeletonFactory',['../classOoT_1_1OoTSkeletonFactory.html',1,'OoT']]],
  ['ootskinanimatedlimbdata_50',['OoTSkinAnimatedLimbData',['../structOoT_1_1OoTSkinAnimatedLimbData.html',1,'OoT']]],
  ['ootskinlimbmodif_51',['OoTSkinLimbModif',['../structOoT_1_1OoTSkinLimbModif.html',1,'OoT']]],
  ['ootskintransformation_52',['OoTSkinTransformation',['../structOoT_1_1OoTSkinTransformation.html',1,'OoT']]],
  ['ootskinvertex_53',['OoTSkinVertex',['../structOoT_1_1OoTSkinVertex.html',1,'OoT']]],
  ['oottextbinaryexporter_54',['OoTTextBinaryExporter',['../classOoT_1_1OoTTextBinaryExporter.html',1,'OoT']]],
  ['oottextdata_55',['OoTTextData',['../structOoT_1_1OoTTextData.html',1,'OoT']]],
  ['oottextfactory_56',['OoTTextFactory',['../classOoT_1_1OoTTextFactory.html',1,'OoT']]],
  ['ootvec3sarraydata_57',['OoTVec3sArrayData',['../classOoT_1_1OoTVec3sArrayData.html',1,'OoT']]],
  ['ootvtxarraydata_58',['OoTVtxArrayData',['../classOoT_1_1OoTVtxArrayData.html',1,'OoT']]],
  ['optionstring_59',['OptionString',['../structBK64_1_1OptionString.html',1,'BK64']]],
  ['orbitview_60',['OrbitView',['../structUI_1_1OrbitView.html',1,'UI']]],
  ['otex_61',['Texture Resource (OTEX)',['../otr_texture.html#autotoc_md36',1,'']]],
  ['otr_20file_20format_20specification_62',['OTR File Format Specification',['../otr_format.html',1,'OTR File Format Specification'],['../otr_format.html#autotoc_md26',1,'OTR File Format Specification']]],
  ['overview_63',['Overview',['../otr_format.html#autotoc_md27',1,'']]],
  ['ovpt_64',['Viewport Resource (OVPT)',['../otr_viewport.html#autotoc_md53',1,'']]],
  ['ovtx_65',['Vertex Resource (OVTX)',['../otr_vertex.html#autotoc_md49',1,'']]]
];
