name: Linux Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Release, Debug]
        standalone: [OFF, ON]
        toolchain: [cmake/toolchain/linux-gnu.cmake, cmake/toolchain/linux-clang.cmake]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install cmake ninja-build libbz2-dev
      - name: Build
        run: |
          cmake -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DUSE_STANDALONE=${{ matrix.standalone }} -DCMAKE_TOOLCHAIN_FILE=${{ matrix.toolchain }}
          cmake --build build-cmake -j
      - name: Create Package
        if: ${{ matrix.config == 'Release' && matrix.standalone == 'ON' }}
        run: |
          mkdir torch-release
          mv build-cmake/torch torch-release/
          cp "$(ldconfig -p | grep libbz2.so.1.0 | tr ' ' '\n' | grep /| head -n1)" torch-release/
      - name: Publish packaged artifacts
        if: ${{ matrix.config == 'Release' && matrix.standalone == 'ON' }}
        uses: actions/upload-artifact@v4
        with:
          name: torch-linux-x64-${{ matrix.toolchain }}
          path: torch-release